### ISSUE TITLE
Check for internet connection after splash screen

### ISSUE THREAD

**Issue by DravitLochan** [BuildmLearn/mConference-Framework#14]
Just after splash screen, if the phone is not connected to internet, the app crashes.
below is the log. can I send a pr with a proper working solution?

`FATAL EXCEPTION: main
                  Process: org.buildmlearn.mconference, PID: 7697
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                      at org.buildmlearn.mconference.secondapproach.HomeRecyclerView.getItemCount(HomeRecyclerView.java:86)
                      at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2556)
                      at android.view.View.measure(View.java:18809)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                      at android.view.View.measure(View.java:18809)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                      at android.view.View.measure(View.java:18809)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:746)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by tejavojjala** [comment]
@DravitLochan i have already submitted a pr #3 regarding this. Forgot to create an issue.

**Comment by DravitLochan** [comment]
I did not see.

**Comment by tejavojjala** [comment]
@DravitLochan can you reopen this issue so that others wont report this again. Also I can reference this issue number in my pr.
